# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Raspberry Pi Pico W (ARM) 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Boost
      run: |
        sudo apt-get -y update
        sudo apt-get -y upgrade
        sudo apt-get -y install libboost-dev
        sudo apt-get -y install libboost-all-dev

    - name: Install ARM Toolchain + deps
      run: |
        sudo apt-get -y update
        sudo apt-get -y install cmake 
        sudo apt-get -y install gcc-arm-none-eabi 
        sudo apt-get -y install libnewlib-arm-none-eabi 
        sudo apt-get -y install build-essential 
        sudo apt-get -y install libstdc++-arm-none-eabi-newlib
      


    - name: Ducktape Boost to ARM toolchain
      run: |
        sudo ln -s /usr/include/boost /usr/lib/gcc/arm-none-eabi/*/include/ 

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

